### ISSUE TITLE
Problem with commit https://github.com/stack-of-tasks/sot-application/pull/3

### ISSUE THREAD

**Issue by SalahBEJI** [stack-of-tasks/sot-application#4]
The pull request https://github.com/stack-of-tasks/sot-application/pull/3
creates a seq fault when trying to connect to the python interpreter.
The reason is still unknown...

**Comment by proyan** [comment]
Can you tell me where the segfault occurs?

**Comment by olivier-stasse** [comment]
That is a problem in itself. It appears when connecting to the interpreter after going through those lines.
It might be a problem of going over the limits.
The best way to see this is to compile the SoT in debug mode and run gdb.

**Comment by proyan** [comment]
I am getting no error with the connection.
If there is a problem with connecting to the interpreter, it is likely that the issue is with the installation.
